spring:
  banner:
    image:
      location: banner.txt

camel:
  springboot:
    name: ShoppingCart
  component:
    servlet:
      allow-java-serialized-object: true
  servlet:
    mapping:
      context-path: "/cart/*"
  dataformat:
    jackson:
      use-list: true

management:
  endpoints:
    web:
      exposure:
        include: mappings,metrics,shutdown


firebase:
  url: "https://shoppingcart-a62bb-default-rtdb.europe-west1.firebasedatabase.app/"
  products: "products.json"
  cartItems: "cartItems.json"

